### ISSUE TITLE
Pls remove 1000 images in repo

### ISSUE THREAD

**Issue by Gellipapa** [project-unk/ox_inventory_redm#2]
Hi! Please don't commit 1000 images in repo but thank you for ox_inventory_redm work. 

Use .gitignore :)

**Comment by egerdnc** [comment]
> 

You can either use the default pictures or just delete them and make your own ones.

**Comment by NewEditOfficial** [comment]
I scrapped around 1k of items from vorp_inventory items, that's why there are many of them, you can just delete them if you don't need them.

The main thing is like plug & play support for these FW, so you dont need to touch it at all. (keeping backwards compatibility)

Thanks for feedback, if you have any ideas, just join us on our discord.
